version: "3.9"

services:
    backend.mysql:
        image: mysql:latest
        ports:
            - 3306:3306
        volumes:
            - ./data:/var/lib/mysql
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - TZ=America/Argentina/Mendoza
        networks:
            - backend

    backend.cloudbeaver:
        image: dbeaver/cloudbeaver:latest
        depends_on:
            - backend.mysql
        restart: always
        ports:
            - '8978:8978'
        volumes:
            - ./cloudbeaver:/opt/cloudbeaver/workspace
        networks:
            - backend

volumes:
    backend.cloudbeaver:
    backend.mysql:

networks:
    backend: